In [16]:
import os
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from skimage.io import imread
from skimage.transform import resize
from skimage.feature import hog
from skimage import util

In [17]:
train_directory = "/content/drive/MyDrive/ANN/images/train"
test_directory = "/content/drive/MyDrive/ANN/images/test"

In [18]:
X_train = [] # Feature
y_train = [] # Label
X_test = []  # Feature
y_test = []  # Label

In [19]:
# HOG parameters for image processing
orientations = 9
pixels_per_cell = (8, 8)
cells_per_block = (2, 2)

In [20]:
# Train directory
for filename in os.listdir(train_directory):
    if filename.endswith('.jpg'):
        digit = filename.split('_')[0] # Find the digit (Label)
        if digit.isdigit():
            file_path = os.path.join(train_directory, filename)

            # Convert the image to grayscale
            image = imread(file_path, as_gray=True)

            # Invert the image to convert black background to white and digits to black
            inverted_image = util.invert(image)
            resized_image = resize(inverted_image, (32, 32))

            # Extract HOG features from the image
            features = hog(resized_image, orientations=orientations, pixels_per_cell=pixels_per_cell,
                           cells_per_block=cells_per_block, transform_sqrt=True)

            X_train.append(features)
            y_train.append(int(digit))

In [21]:
X_train = np.array(X_train)
y_train = np.array(y_train)

In [22]:
print(y_train)

[9 9 8 ... 0 0 0]


In [23]:
# Test directory
for filename in os.listdir(test_directory):
    if filename.endswith('.jpg'):
        digit = filename.split('_')[0] # Find the digit (Label)
        if digit.isdigit():
            file_path = os.path.join(test_directory, filename)

            # Convert it to grayscale
            image = imread(file_path, as_gray=True)

            # Invert the image to convert black background to white and digits to black
            inverted_image = util.invert(image)
            resized_image = resize(inverted_image, (32, 32))

            # Extract HOG features from the image
            features = hog(resized_image, orientations=orientations, pixels_per_cell=pixels_per_cell,
                           cells_per_block=cells_per_block, transform_sqrt=True)

            X_test.append(features)
            y_test.append(int(digit))

In [24]:
X_test = np.array(X_test)
y_test = np.array(y_test)

In [25]:
print(X_test)

[[0.24807377 0.30620859 0.00716252 ... 0.00609932 0.01284834 0.00312218]
 [0.36383077 0.00301858 0.02113691 ... 0.00161071 0.         0.00588059]
 [0.01410621 0.00248402 0.00047026 ... 0.00157772 0.00086577 0.00432994]
 ...
 [0.0646677  0.02761928 0.02048782 ... 0.0022965  0.00065398 0.00966703]
 [0.02074383 0.09662244 0.02284761 ... 0.         0.00232383 0.0045783 ]
 [0.01192108 0.00301586 0.01026978 ... 0.00503752 0.0049584  0.01205068]]


In [26]:
# Create an MLP classifier
clf = MLPClassifier(hidden_layer_sizes=(100,), max_iter=1000)

In [27]:
# Train the classifier on the training set
clf.fit(X_train, y_train)

MLPClassifier(max_iter=1000)

In [28]:
# Predict the labels for the test set
y_pred = clf.predict(X_test)

In [29]:
print(y_pred)

[4 2 1 ... 0 0 0]


In [30]:
# Calculate the accuracy of the classifier
test_accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", test_accuracy)

Accuracy: 0.9586447433981067
